version: "3.9" # optional since v1.27.0

services:
 webserver:
   image: nareshreddy1238/ecomm
   ports:
     - "8080:80"
   volumes:
     - webapp:/data
   networks:
     mynetwork1:
       ipv4_address: 192.1.4.1

 
 nginx1:
   image: nareshreddy1238/nginx:ubuntu
   ports:
     - "8081:80"
   volumes:
     - webapp:/data
   networks:
     mynetwork1:
       ipv4_address: 192.1.4.2


 nginx2:
   image: nareshreddy1238/nginx:centos
   ports:
     - "8082:80"
   volumes:
     - webapp:/data
   networks:
     mynetwork1:
       ipv4_address: 192.1.4.3


 nodejs_server:
   image: nareshreddy1238/nodejs:ubuntu
   ports:
     - "8083:8080"
   volumes:
     - webapp:/home/node/app
   networks:
     mynetwork1:
       ipv4_address: 192.1.4.4

volumes:
 webapp:
   external: true
networks:
 mynetwork1:
   external: true

          

